import Head from 'next/head'
import Skills from '../components/Skills'
import About from '../components/About'
import Main from '../components/Main'
import Navbar from '../components/Navbar'
import Projects from '../components/Projects'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Greg, aspiring Frontend Developer</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
        <Navbar/>
        <Main />
        <About/>
        <Skills/>
        <Projects/>
    </div>
  )
}
